apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: project
data:
  TODO_BACKEND_URL: http://todo-backend:2345
  PICSUM_BASE_URL: https://picsum.photos
  IMAGE_URL_FILE_PATH: /usr/src/app/files/image-url.txt
  PORT: "5001"