apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      volumes:
        - name: shared-files
          emptyDir: {}
      containers:
        - name: todo
          image: europe-north1-docker.pkg.dev/devopswithkubernetes-509407/dwk-repo/todo:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: shared-files
              mountPath: /usr/src/app/files
          envFrom:
            - configMapRef:
                name: todo-config
          resources:
            requests:
              cpu: "20m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"