apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: shared-pvc
      containers:
        - name: todo
          image: nuuttinyyssonen/todo:latest
          volumeMounts:
            - name: shared-files
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: "5001"