apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - ingress.yaml

images:
  - name: europe-north1-docker.pkg.dev/devopswithkubernetes-509407/dwk-repo/todo
    newTag: done-v1
