apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-files
          emptyDir: {}
      containers:
        - name: writer
          image: log-output-writer:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: shared-files
              mountPath: /usr/src/app/files
        - name: reader
          image: log-output-reader:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: shared-files
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: "3000"