apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-config
  namespace: project
data:
  PORT: "3000"
  POSTGRES_HOST: postgres-todo
  POSTGRES_USER: postgres
  POSTGRES_DB: postgres
  NATS_URL: nats://nats:4222