apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../todo/manifests
  - ../../todo-backend/manifests
  - ../../todo-backend/manifests/backup-cronjob.yaml
  - ../../broadcaster/manifests
  - ../nats.yaml
  - backup-serviceaccount.yaml

images:
  - name: europe-north1-docker.pkg.dev/devopswithkubernetes-509407/dwk-repo/todo
    newTag: done-v1
  - name: europe-north1-docker.pkg.dev/devopswithkubernetes-509407/dwk-repo/todo-backend
    newTag: nats-v1
  - name: europe-north1-docker.pkg.dev/devopswithkubernetes-509407/dwk-repo/broadcaster
    newTag: latest